# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0010_auto_20180414_2058'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMedia',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_background_media_backgroundmedia', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('height', models.CharField(default='100%', help_text='Height in pixels or %', max_length=50, verbose_name='container height')),
                ('add_style', models.BooleanField(default=True, help_text='Link default style sheet', verbose_name='add style')),
                ('overlay', models.CharField(blank=True, help_text='To add a css overlay enter the colour of the overlay, e.g. rgba(0,0,0,0.7)', max_length=25, null=True, verbose_name='overlay')),
                ('image_position', models.CharField(default='center center', help_text='The css position of the image', max_length=50, verbose_name='image position')),
                ('vide_json_config', models.TextField(blank=True, help_text='The optional js object for the vide config. Click <a href="https://github.com/VodkaBears/Vide" target="_blank"> here</a> for more info.', null=True, verbose_name='Vide.js config')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
                ('video_mp4', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_mp4', to='filer.File', verbose_name='Video mp4')),
                ('video_ogv', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_ogv', to='filer.File', verbose_name='Video ogv')),
                ('video_poster', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Video poster')),
                ('video_webm', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_webm', to='filer.File', verbose_name='Video webm')),
            ],
            options={
                'verbose_name': 'Background Media',
                'verbose_name_plural': 'Background Media',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
