# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_background_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundmedia',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_background_media_backgroundmedia', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='backgroundmedia',
            name='height',
            field=models.CharField(default='100%', help_text='height in pixels or %', max_length=100, verbose_name='container height'),
        ),
        migrations.AlterField(
            model_name='backgroundmedia',
            name='video_webm',
            field=models.FileField(blank=True, help_text='Video in the webm format', null=True, upload_to='videos/djangocms_bg_media', verbose_name='video webm'),
        ),
    ]
