# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 09:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_background_media', '0002_auto_20180611_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundmedia',
            name='add_style',
            field=models.BooleanField(default=True, help_text='Link default style sheet', verbose_name='add style'),
        ),
        migrations.AlterField(
            model_name='backgroundmedia',
            name='height',
            field=models.CharField(default='100%', help_text='Height in pixels or %', max_length=50, verbose_name='container height'),
        ),
        migrations.AlterField(
            model_name='backgroundmedia',
            name='image_position',
            field=models.CharField(default='center center', help_text='The css position of the image', max_length=50, verbose_name='image position'),
        ),
        migrations.AlterField(
            model_name='backgroundmedia',
            name='overlay',
            field=models.CharField(blank=True, help_text='To add a css overlay enter the colour of the overlay, e.g. rgba(0,0,0,0.7)', max_length=25, null=True, verbose_name='overlay'),
        ),
        migrations.AlterField(
            model_name='backgroundmedia',
            name='vide_json_config',
            field=models.TextField(blank=True, help_text='The optional js object for the vide config. Click <a href="https://github.com/VodkaBears/Vide" target="_blank"> here</a> for more info.', null=True, verbose_name='Vide.js config'),
        ),
        migrations.AlterField(
            model_name='backgroundmedia',
            name='video_mp4',
            field=models.FileField(blank=True, help_text='Video in the mp4 format', null=True, upload_to='videos/djangocms_bg_media', verbose_name='Video mp4'),
        ),
        migrations.AlterField(
            model_name='backgroundmedia',
            name='video_ogv',
            field=models.FileField(blank=True, help_text='Video in the ogv format', null=True, upload_to='videos/djangocms_bg_media', verbose_name='Video ogv'),
        ),
        migrations.AlterField(
            model_name='backgroundmedia',
            name='video_poster',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Video poster'),
        ),
        migrations.AlterField(
            model_name='backgroundmedia',
            name='video_webm',
            field=models.FileField(blank=True, help_text='Video in the webm format', null=True, upload_to='videos/djangocms_bg_media', verbose_name='Video webm'),
        ),
    ]
